config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'signin', to: 'users#signin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    include BCrypts

    validates :email, presence: true
    validates :name, presence: true

    def password=(new_password)
        self.password_digest = Password.create(new_password)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params.except(:password_confirmation))
        if user_params[:password_confirmation] == user_params[:password]    
            if @user.save
                redirect_to root_path
            else
                render 'new'
            end
        else
            @user.errors.add(:password, 'Password correspond pas')
            render 'new'
        end
    end

    def signin
        
    end

    private
        def user_params
            @user_params ||= params.require(:user).permit(:email, :name, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MatTwitter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    - if @current_user
      = render "navbar/connected"
    - else
      = render "navbar/disconnected"

    %section.container
      = yield

app/views/navbar/_connected.html.haml
= nav_bar brand: "MatTwitter", brand_link: root_path do
    = menu_group do
        = menu_item "Profil", root_path
        = menu_item "All messages", root_path
        = menu_item "Message from user", root_path

app/views/navbar/_disconnected.html.haml
= nav_bar brand: "MatTwitter", brand_link: root_path do
    = menu_group do
        = menu_item "Sign in", signin_path
        = menu_item "Sign up", signup_path

app/views/users/connect.html.haml
%form
  .form-group
    %label{:for => "inputEmail"} Email address
    %input#inputEmail.form-control{"aria-describedby" => "emailHelp", :placeholder => "Enter email", :type => "email"}/
    %small#emailHelp.form-text.text-muted We'll share your email with huge company for money.
  .form-group
    %label{:for => "inputPassword"} Password
    %input#inputPassword.form-control{:placeholder => "Password", :type => "password"}/
  .form-group.form-check
    %input#exampleCheck.form-check-input{:type => "checkbox"}/
    %label.form-check-label{:for => "exampleCheck"} Check me out
  %button.btn.btn-primary{:type => "submit"} Submit

app/views/users/new.html.haml
- if @user.errors.any?
  = @user.errors.full_messages

= form_for @user, url: signup_path do |form|
  %p
    = form.label :email
    %br/
    = form.text_field :email, class: 'form-control', type: 'email'
  %p
    = form.label :name
    %br/
    = form.text_field :name, class: 'form-control', type: 'name'
  %p
    = form.label :password
    %br/
    = form.text_field :password, class: 'form-control', value: '', type: 'password'
  %p
    = form.label :password_confirmation
    %br/
    = form.text_field :password_confirmation, class: 'form-control', type: 'password', value: ''
  %p
    = form.submit class: 'btn btn-primary'

app/views/users/signin.html.haml
%form
  .form-group
    %label{:for => "inputEmail"} Email address
    %input#inputEmail.form-control{"aria-describedby" => "emailHelp", :placeholder => "Enter email", :type => "email", :required => ""}/
    %small#emailHelp.form-text.text-muted We'll share your email with huge company for money.
  .form-group
    %label{:for => "inputPassword"} Password
    %input#inputPassword.form-control{:placeholder => "Password", :type => "password", :required => ""}/
  .form-group.form-check
    %input#exampleCheck.form-check-input{:type => "checkbox"}/
    %label.form-check-label{:for => "exampleCheck"} Check me out
  %button.btn.btn-primary{:type => "submit"} Submit